#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Key_Ref_02.generated.h"

UCLASS()
class CPPCOMP_UE532_API AKey_Ref_02 : public AActor{
	GENERATED_BODY()
	
public:	
	AKey_Ref_02();

	// --> right click on UPROPERTY in VS and check declaration -- 

	// Check This !! ToolTip from C++ code for int Value_01 ... 
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "KeyRef_02 integer")
		int Value_01;

	//.. multiline 
	// ..        comments .... <-- use this please  !!!
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category = "KeyRef_02 Float")
		float Value_02;

	/*
	.. multiline line 1 
	.. .. ... .. ... multiline line 2
	*/
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category = "KeyRef_02 Bool")
		bool Flag_01;

	
	UPROPERTY(BlueprintReadWrite, EditInstanceOnly, Category = "KeyRef_02 Actor")
		AActor* Object_01;

	// .. your comment for BlueprintReadWrite Value_A
	UPROPERTY(BlueprintReadWrite, Category = "KeyRef_02 Value A")
		int Value_A;

	// .. your comment for BlueprintReadOnly Value_B
	UPROPERTY(BlueprintReadOnly, Category = "KeyRef_02 Value B")
		int Value_B;

	// https://docs.unrealengine.com/en-US/Programming/UnrealArchitecture/Reference/Properties/Specifiers/index.html  Property Specifiers
	// https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-5-3-documentation?application_version=5.3
	// ---------------------------------------------------------------------------

	// Player Skill level 
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "KeyRef_02 Skill", meta = (DisplayName = "Skill Level"))
		int Value_C_01;

	// Player Skill overdrive range
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "KeyRef_02 Skill", meta = (DisplayName = "Overdrive", ClampMin = "-12", ClampMax = "12"))
		int Value_C_02;

	// https://docs.unrealengine.com/en-US/Programming/UnrealArchitecture/Reference/Metadata/index.html  Metadata Specifiers
	// https://dev.epicgames.com/documentation/en-us/unreal-engine/metadata-specifiers-in-unreal-engine?application_version=5.3

	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "KeyRef_02 Skill")
		int Value_C_03;

	// --> right click on UFUNCTION in VS and check declaration --

	// check activation
	UFUNCTION(BlueprintCallable, Category = "KeyRef_02 Functions")
		bool isActive();
	// check extra 
	UFUNCTION(BlueprintPure, Category = "KeyRef_02 Functions")
		bool isExtra();

	/// This function is designed to be overridden by a blueprint.  Do not provide a body for this function;
	/// the autogenerated code will include a thunk that calls ProcessEvent to execute the overridden body.
	//BlueprintImplementableEvent,

	/// This function is designed to be overridden by a blueprint, but also has a native implementation.
	/// Provide a body named [FunctionName]_Implementation instead of [FunctionName]; the autogenerated
	/// code will include a thunk that calls the implementation method when necessary.
	//BlueprintNativeEvent,


	// set skill 
	UFUNCTION(BlueprintImplementableEvent, Category = "KeyRef_02 Events")
		void SkillSet();

	// control skill
	UFUNCTION(BlueprintNativeEvent, Category = "KeyRef_02 Events")
		void SkillControl();

	// get and set values by event
	// https://answers.unrealengine.com/questions/57955/return-a-value-from-a-blueprintimplementableevent.html
	// https://answers.unrealengine.com/questions/338927/pass-tassetptr-to-blueprintimplementableevent.html <-- TArray exceptions 

	// control maximum skill
	UFUNCTION(BlueprintNativeEvent, Category = "KeyRef_02 Events")
		bool SkillMAX();



protected:
	virtual void BeginPlay() override;

public:	
	virtual void Tick(float DeltaTime) override;

	// funtions - void
	void setDistance();
	void setName(FString name);
	void setActive(bool bActive = true);

	// functiona parameter with default value 
	//void setActive_PRO(bool bActive, int value);
	//void setActive_PRO(int value, bool bActive);	
	//void setActive_PRO(bool bActive, int value);	
	//void setActive_PRO(int value, bool bActive, int set, bool bExtra); 

	// functions with return value
	int getDistance();
	FString getName(int id);
	bool Flag_018 = true;
};
